!!com.snobot.simulator.config.v1.SimulatorConfigV1
mAccelerometers: []
mAnalogIn: []
mAnalogOut: []
mDefaultI2CWrappers: {}
mDefaultSpiWrappers: {}
mDigitalIO: []
mEncoders: []
mGyros: []
mPwm:
- mHandle: 1
  mMotorModelConfig: null
  mMotorSimConfig: null
  mName: Speed Controller 1
  mType: com.snobot.simulator.module_wrapper.wpi.WpiPwmWrapper
- mHandle: 2
  mMotorModelConfig: null
  mMotorSimConfig: null
  mName: Speed Controller 2
  mType: com.snobot.simulator.module_wrapper.wpi.WpiPwmWrapper
- mHandle: 3
  mMotorModelConfig: null
  mMotorSimConfig: null
  mName: Speed Controller 3
  mType: com.snobot.simulator.module_wrapper.wpi.WpiPwmWrapper
- mHandle: 4
  mMotorModelConfig: null
  mMotorSimConfig: null
  mName: Speed Controller 4
  mType: com.snobot.simulator.module_wrapper.wpi.WpiPwmWrapper
- mHandle: 5
  mMotorModelConfig: null
  mMotorSimConfig: null
  mName: Speed Controller 5
  mType: com.snobot.simulator.module_wrapper.wpi.WpiPwmWrapper
- mHandle: 6
  mMotorModelConfig: null
  mMotorSimConfig: null
  mName: Speed Controller 6
  mType: com.snobot.simulator.module_wrapper.wpi.WpiPwmWrapper
- mHandle: 7
  mMotorModelConfig: null
  mMotorSimConfig: null
  mName: Speed Controller 7
  mType: com.snobot.simulator.module_wrapper.wpi.WpiPwmWrapper
- mHandle: 8
  mMotorModelConfig: null
  mMotorSimConfig: null
  mName: Speed Controller 8
  mType: com.snobot.simulator.module_wrapper.wpi.WpiPwmWrapper
- mHandle: 9
  mMotorModelConfig: null
  mMotorSimConfig: null
  mName: Speed Controller 9
  mType: com.snobot.simulator.module_wrapper.wpi.WpiPwmWrapper
- mHandle: 10
  mMotorModelConfig: null
  mMotorSimConfig: null
  mName: Speed Controller 10
  mType: com.snobot.simulator.module_wrapper.wpi.WpiPwmWrapper
mRelays: []
mSimulatorComponents: []
mSolenoids: []
